### ISSUE TITLE
return the image path

### ISSUE THREAD

**Issue by mayroncachina** [devgeeks/Canvas2ImagePlugin#15]
that will have the possibility to return the full path of the image on function return?

**Comment by nicola3344** [comment]
Just a FYI, I've modified the plugin to be able to get the assetURL in the success callback. For that I use ALAssetsLibrary writeImageToSavedPhotosAlbum instead of UIImageWriteToSavedPhotosAlbum. I'll try to do a pull request as soon as I understant how git works.
