### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by InductiveIdeas** [devgeeks/Canvas2ImagePlugin#19]
Hey Devgeek.  Thanks for responding to and getting a fix out for the xcode errors I was getting.  I created a brand new app to test out the plugin and it builds just fine no errors. So awesome, thanks.

I hope I'm not missing something completely trivial but I an getting this error:
"undefined is not an object (evaluating window.canvas2ImagePlugin.saveImageDataToLibrary() )"

I basically put your example javascript code in an onclick where I was populating the canvas with an image before it would save, here's the code:

``` javascript
function uploadImage() {
    var canvas = document.getElementById("myCanvas");
    var context = canvas.getContext("2d");

    var imageObj = new Image();
    imageObj.src = "http://www.kodyaz.com/images/windows-8-screenshots/consumer-beta-windows-8-start-screen.png";

    imageObj.onload = function () {
        context.drawImage(imageObj, 0, 0);
    };

    window.canvas2ImagePlugin.saveImageDataToLibrary(
        function(msg){
        console.log(msg);
        },
        function(err){
        console.log(err);
        },
        document.getElementById('myCanvas')
        );
}
```

Am I missing something, or using the plugin wrong?

**Comment by sankari123** [comment]
I tried your code in Sony and ASUS tab. I could not store the file locally (gallery / Pictures)
 Step 1 - <button id=btn4 onclick="savePhoto();" class="btn4css">
Step 2 - onDeviceReady() included--  var clickme = document.getElementById("btn4");
btn4.addEventListener('click', savePhoto);

step 3 -  function savePhoto()


function savePhoto()
{
var canvas=document.getElementById("theCanvas");
	var ctx=c.getContext("2d");
	tmp = ctx.getImageData(0,0,canvas.width, canvas.height);
		imgDataUrl = canvas.toDataURL(); 

	var imageObj = new Image();
    imageObj.src = imgDataUrl;
	imageObj.onload = function () {
        context.drawImage(imageObj, 0, 0);
            window.canvas2ImagePlugin.saveImageDataToLibrary(
            function(msg){
                console.log(msg);
            },
            function(err){
                console.log(err);
            },
            document.getElementById('theCanvas')
        );
    };
}
