### ISSUE TITLE
On Phonegap Build (PGB) Plugin Not Installed?

### ISSUE THREAD

**Issue by jdivis** [devgeeks/Canvas2ImagePlugin#57]
After uploading and building my app with the Canvas2ImagePlugin configured, I see Canvas2Image in the plugins list, but the installed version is N/A. 

Plugin	                                             Source	Version	Latest	Installed	Platforms
org.devgeeks.canvas2imageplugin   	pgb	           0.6.0	0.6.0	    n/a	android,ios,winphone

I've tried downgrading from cli-5.2.0 to 3.0, but with no luck. 

Is there anything else I need to be doing to get PGB to install the plugin?

**Comment by devgeeks** [comment]
Not sure. I'll try and have a look. The latest version on npm is 0.7.0.

**Comment by jdivis** [comment]
Blarg. I had actually tried earlier using source="npm" but received an error. Just tried with updating the version to 0.7.0, and received:

Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: org.devgeeks.canvas2imageplugin@0.7.0

I removed the version, but then received:

Error - The following plugin, plugin version or a dependancy of this plugin is not on npm: org.devgeeks.canvas2imageplugin

**Comment by devgeeks** [comment]
The plugin IDs are different on npm:

`cordova-plugin-canvas2image`

**Comment by devgeeks** [comment]
https://www.npmjs.com/package/cordova-plugin-canvas2image

**Comment by jdivis** [comment]
You are a scholar and a gentleman, sir! Thank you!
