### ISSUE TITLE
Canvas image need to save with white background

### ISSUE THREAD

**Issue by hypesol** [devgeeks/Canvas2ImagePlugin#79]
I am using this plugin but this save Image with black background. I need to save image with white background. any solution please guide me. thanks

**Comment by devgeeks** [comment]
The black background is because the image has a transparent background.

See Issue #9

**Comment by hypesol** [comment]
Yes you are write but I am making color fill background and when I save image empty area always save with black background. It should be white or with other color which I set default. so please give me solution for this. thanks

**Comment by hypesol** [comment]
And as you give the solution in issue #9 start canvas with any colored background that is not working here. I have also tried that.
