### ISSUE TITLE
Canvas Image saved with black background

### ISSUE THREAD

**Issue by jsphkhan** [devgeeks/Canvas2ImagePlugin#9]
First of all thanks a lot for the great work and your plugin. I have been able to use it successfully with my Phonegap 2.2 iOS project. The only issue I am facing is that the Canvas image is saved with a black background. Is there anyway to get a white background? My application is a Canvas Paint program and hence I need to save the image in a white background color. Please help me out.
I had one more doubt. How do I get the saved image path? I need to email the image using EMailComposer plugin. 
Thanks in advance.
Joseph

**Comment by loki4u** [comment]
@jsphkhan could you please share the snippet for converting transparent to white background in cordova canvas.

**Comment by hypesol** [comment]
I also need this solution if you can provide ... thanks in advance.
